name: onlinefooddeliverysystem
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cached_network_image: ^3.2.0
  carousel_slider: ^4.0.0
  cloud_firestore: ^3.1.1
  cupertino_icons: ^1.0.2
  device_preview: ^1.0.0
  bot_toast: ^4.0.1
  dio: ^4.0.4
  equatable: ^2.0.3
  firebase_core: ^1.10.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  shared_preferences: ^2.0.11
  shimmer: ^2.0.0
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  # To add assets to your application:
  assets:
    - assets/images/
    - assets/images/brand/
# Fonts:
fonts:
  - family: Cairo
    fonts:
      - asset: fonts/Cairo-Regular.ttf
      - asset: fonts/Cairo-ExtraLight.ttf
        weight: 100
      - asset: fonts/Cairo-Light.ttf
        weight: 200
      - asset: fonts/Cairo-Medium.ttf
        weight: 500
      - asset: fonts/Cairo-Bold.ttf
        weight: 600
      - asset: fonts/Cairo-Black.ttf
        weight: 700
